apiVersion: v1
kind: Secret
metadata:
  name: clearml-conf
data:
  apiserver_key: {{ .Values.clearml.apiserverKey | b64enc }}
  apiserver_secret: {{ .Values.clearml.apiserverSecret | b64enc }}
  fileserver_key: {{ .Values.clearml.fileserverKey | b64enc }}
  fileserver_secret: {{ .Values.clearml.fileserverSecret | b64enc }}
  apps_agent_key: {{ .Values.enterpriseFeatures.apps.AgentKey | b64enc }}
  apps_agent_secret: {{ .Values.enterpriseFeatures.apps.AgentSecret | b64enc }}
  secure_auth_token_secret: {{ .Values.clearml.secureAuthTokenSecret | b64enc }}
  apps_git_agent_user: {{ .Values.enterpriseFeatures.apps.GitAgentUser | b64enc }}
  apps_git_agent_pass: {{ .Values.enterpriseFeatures.apps.GitAgentPass | b64enc }}
  test_user_key: {{ .Values.clearml.testUserKey | b64enc }}
  test_user_secret: {{ .Values.clearml.testUserSecret | b64enc }}
---
{{- if .Values.imageCredentials.enabled }}
{{- if not .Values.imageCredentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: clearml-registry-key
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
{{- end }}
