apiVersion: v2
name: clearml-agent
description: MLOps platform Task running agent
type: application
version: "5.2.0"
appVersion: "1.24"
kubeVersion: ">= 1.21.0-0 < 1.30.0-0"
home: https://clear.ml
icon: https://raw.githubusercontent.com/allegroai/clearml/master/docs/clearml-logo.svg
sources:
  - https://github.com/allegroai/clearml-helm-charts
  - https://github.com/allegroai/clearml
maintainers:
  - name: valeriano-manassero
    url: https://github.com/valeriano-manassero
keywords:
  - clearml
  - "machine learning"
  - mlops
  - "task agent"
annotations:
  artifacthub.io/changes: |
    - kind: feature
      description: Support for multiple queues
