apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    clearml.serving.service: clearml-serving-inference
  name: clearml-serving-inference
spec:
  replicas: 1
  selector:
    matchLabels:
      clearml.serving.service: clearml-serving-inference
  strategy: {}
  template:
    metadata:
      annotations: {}
      labels:
        clearml.serving.network/clearml-serving-backend: "true"
        clearml.serving.service: clearml-serving-inference
    spec:
      containers:
        - env:
            - name: CLEARML_API_ACCESS_KEY
              value: "{{ .Values.clearml.apiAccessKey }}"
            - name: CLEARML_API_SECRET_KEY
              value: "{{ .Values.clearml.apiSecretKey }}"
            - name: CLEARML_API_HOST
              value: "{{ .Values.clearml.apiHost }}"
            - name: CLEARML_FILES_HOST
              value: "{{ .Values.clearml.filesHost }}"
            - name: CLEARML_WEB_HOST
              value: "{{ .Values.clearml.webHost }}"
            - name: CLEARML_DEFAULT_KAFKA_SERVE_URL
              value: clearml-serving-kafka:9092
            - name: CLEARML_SERVING_POLL_FREQ
              value: "1.0"
            - name: CLEARML_DEFAULT_BASE_SERVE_URL
              value: http://127.0.0.1:8080/serve
            - name: CLEARML_DEFAULT_TRITON_GRPC_ADDR
              value: ""
            - name: CLEARML_SERVING_NUM_PROCESS
              value: "2"
            - name: CLEARML_SERVING_PORT
              value: "8080"
            - name: CLEARML_SERVING_TASK_ID
              value: "{{ .Values.clearml.servingTaskId }}"
            - name: CLEARML_USE_GUNICORN
              value: "true"
            {{- if .Values.clearml.extraPythonPackages }}
            - name: EXTRA_PYTHON_PACKAGES
              value: '{{ join " " .Values.clearml.extraPythonPackages }}'
            {{- end }}
          image: "{{ .Values.clearml_serving_inference.image }}:{{ .Chart.AppVersion }}"
          name: clearml-serving-inference
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
