apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    clearml.serving.service: {{ include "clearml-serving.fullname" . }}-statistics
  name: {{ include "clearml-serving.fullname" . }}-statistics
spec:
  replicas: 1
  selector:
    matchLabels:
      clearml.serving.service: {{ include "clearml-serving.fullname" . }}-statistics
  strategy: {}
  template:
    metadata:
      annotations: {}
      labels:
        clearml.serving.network/clearml-serving-backend: "true"
        clearml.serving.service: {{ include "clearml-serving.fullname" . }}-statistics
    spec:
      containers:
        - env:
            - name: CLEARML_API_ACCESS_KEY
              value: "{{ .Values.clearml.apiAccessKey }}"
            - name: CLEARML_API_SECRET_KEY
              value: "{{ .Values.clearml.apiSecretKey }}"
            - name: CLEARML_API_HOST
              value: "{{ .Values.clearml.apiHost }}"
            - name: CLEARML_FILES_HOST
              value: "{{ .Values.clearml.filesHost }}"
            - name: CLEARML_WEB_HOST
              value: "{{ .Values.clearml.webHost }}"
            - name: CLEARML_DEFAULT_KAFKA_SERVE_URL
              value: {{ include "clearml-serving.fullname" . }}-kafka:9092
            - name: CLEARML_SERVING_POLL_FREQ
              value: "1.0"
            - name: CLEARML_SERVING_TASK_ID
              value: "{{ .Values.clearml.servingTaskId }}"
            {{- if .Values.clearml_serving_statistics.extraPythonPackages }}
            - name: EXTRA_PYTHON_PACKAGES
              value: '{{ join " " .Values.clearml_serving_statistics.extraPythonPackages }}'
            {{- end }}
          image: "{{ .Values.clearml_serving_statistics.image.repository }}:{{ .Values.clearml_serving_statistics.image.tag }}"
          name: {{ include "clearml-serving.fullname" . }}-statistics
          ports:
            - containerPort: 9999
          resources: {}
      restartPolicy: Always
