apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    clearml.serving.service: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      clearml.serving.service: kafka
  strategy: {}
  template:
    metadata:
      annotations: {}
      labels:
        clearml.serving.network/clearml-serving-backend: "true"
        clearml.serving.service: kafka
    spec:
      containers:
        - env:
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: PLAINTEXT://clearml-serving-kafka:9092
            - name: KAFKA_CFG_LISTENERS
              value: PLAINTEXT://0.0.0.0:9092
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: clearml-serving-zookeeper:2181
            - name: KAFKA_CREATE_TOPICS
              value: '"topic_test:1:1"'
          image: "{{ .Values.kafka.image.repository }}:{{ .Values.kafka.image.tag }}"
          name: clearml-serving-kafka
          ports:
            - containerPort: 9092
          resources: {}
      restartPolicy: Always
