apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    clearml.serving.service: zookeeper
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      clearml.serving.service: zookeeper
  strategy: {}
  template:
    metadata:
      annotations: {}
      labels:
        clearml.serving.network/clearml-serving-backend: "true"
        clearml.serving.service: zookeeper
    spec:
      containers:
        - env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
          image: {{ .Values.zookeeper.image }}
          name: clearml-serving-zookeeper
          ports:
            - containerPort: 2181
          resources: {}
      restartPolicy: Always
